//authorization
export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_LOCALY = 'SIGN_IN_LOCALY';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const LOAD_FINISH = 'LOAD_FINISH';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const RESET_TIMEOUT_ID = 'RESET_TIMEOUT_ID';
export const LOGOUT = 'LOGOUT';

//topics
export const GET_TOPICS = 'GET_TOPICS';
export const START_FETCHING = 'START_FETCHING';
export const TOPICS_ERROR = 'TOPICS_ERROR';
export const FINISH_FETCHING = 'FINISH_FETCHING';
export const ADD_TOPIC = 'ADD_TOPIC';
export const DELETE_TOPIC = 'DELETE_TOPIC';
export const EDIT_TOPIC = 'EDIT_TOPIC';
export const SET_CURRENT_TOPIC = 'SET_CURRENT_TOPIC';
export const SUBSCRIBE_USER_TO_ROOMS = 'SUBSCRIBE_USER_TO_ROOMS';
export const LOGOUT_TOPICS = 'LOGOUT_TOPICS';

//socket.io
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';

//messages
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_SAVE = 'MESSAGE_SAVE';
export const START_MESSAGES_SAVING = 'START_MESSAGES_SAVING';
export const FINISH_MESSAGES_SAVING = 'FINISH_MESSAGES_SAVING';
export const START_MESSAGES_FETCHING = 'START_MESSAGES_FETCHING';
export const FINISH_MESSAGES_FETCHING = 'FINISH_MESSAGES_FETCHING';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const START_MESSAGES_RECIVE = 'START_MESSAGES_RECIVE';
export const FINISH_MESSAGES_RECIVE = 'FINISH_MESSAGES_RECIVE';
export const LOGOUT_MESSAGES = 'LOGOUT_MESSAGES';

